A j footer source repo
ucsb-cs156-f22/f22-7pm-courses pull request #13
Opened 2022-11-19 05:06 UTC by Abelatnafu

Abel & Junhwan Lee
- [x] Change the footer component so that it gets the value of the URL for the source repo from /api/systeminfo.
<img width="1389" alt="Screenshot 2022-11-18 at 9 05 32 PM" src="https://user-images.githubusercontent.com/69553149/202835238-7aeb9663-c91a-427f-adcb-5ec20d55f7cd.png">

- [x] Modified tests on both backend and frontend.
- [x] Modified the fixtures for systemInfo.
- [x] Modified storybook to reflect the changes in the footer.
<img width="1440" alt="Screenshot 2022-11-18 at 9 04 53 PM" src="https://user-images.githubusercontent.com/69553149/202835216-6ee0fa0c-ec56-43f7-ac3a-11975375e212.png">

2022-11-21 04:17 UTC, masonma21 submitted a review, later dismissed
LGTM!

2022-11-21 23:35 UTC, pconrad requested changes
Looks great!  Just one small nitpick (that you would have had no way of knowing, probably, but let's get this fixed before we merge it.)

2022-11-21 23:35 UTC, pconrad commented on frontend/src/main/utils/systemInfo.js
> +        sourceRepoUrl:"https://github.com/ucsb-cs156-s22/s22-4pm-courses",
Minor nitpick: but can we change the default value here to the following?  That is a better long-term choice as a default:

```
https://github.com/ucsb-cs156/proj-courses
```

2022-11-21 23:35 UTC, pconrad commented on frontend/src/main/utils/systemInfo.js
> +      sourceRepoUrl:"https://github.com/ucsb-cs156-s22/s22-4pm-courses",
Same as previous comment:
`https://github.com/ucsb-cs156/proj-courses`

2022-11-21 23:35 UTC, pconrad commented on frontend/src/tests/utils/systemInfo.test.js
> +                sourceRepoUrl: "https://github.com/ucsb-cs156-s22/s22-4pm-courses",
Same here: `https://github.com/ucsb-cs156/proj-courses`

2022-11-21 23:35 UTC, pconrad commented on frontend/src/tests/utils/systemInfo.test.js
> +                sourceRepoUrl : "https://github.com/ucsb-cs156-s22/s22-4pm-courses",
Same here: `https://github.com/ucsb-cs156/proj-courses`

2022-11-21 23:35 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/courses/services/SystemInfoServiceImpl.java
> +  @Value("${app.sourceRepoUrl:https://github.com/ucsb-cs156-s22/s22-4pm-courses}")
Same here: `https://github.com/ucsb-cs156/proj-courses`

2022-11-21 23:35 UTC, pconrad commented on src/test/java/edu/ucsb/cs156/courses/controllers/SystemInfoControllerTests.java
> +        .sourceRepoUrl("https://github.com/ucsb-cs156-s22/s22-4pm-courses")
This one can stay like this; since you are testing specific values.

2022-11-21 23:35 UTC, pconrad commented on src/test/java/edu/ucsb/cs156/courses/controllers/SystemInfoControllerTests.java
> +        .sourceRepoUrl("https://github.com/ucsb-cs156-s22/s22-4pm-courses")
This one can stay like this; since you are testing specific values.

2022-11-21 23:35 UTC, pconrad commented on src/test/java/edu/ucsb/cs156/courses/controllers/SystemInfoControllerTests.java
> +        .sourceRepoUrl("https://github.com/ucsb-cs156-s22/s22-4pm-courses")
This one can stay like this; since you are testing specific values.

2022-11-23 02:16 UTC, masonma21 approved these changes
LGTM!

2022-11-23 20:50 UTC, pconrad approved these changes
LGTM!

2022-11-23 20:51 UTC, merged