HY & AG - Personal schedule dropdown component
ucsb-cs156-f22/f22-7pm-courses pull request #26
Opened 2022-11-23 02:05 UTC by HansonYu23

Created a Personal Schedule dropdown list that shows all personal schedules in the format "id - QYY - name". Personal Schedules can be selected from this dropdown list and the state of the form should reflect the Personal Schedule selected. All frontend tests and mutation tests are passing on local machines. 

Resolves  #3

2022-11-23 20:43 UTC, pconrad commented
@HansonYu23 Typically, it's only the staff (instructors, TAs, LAs) that add the labels for points.  But your suggestion that this may be a 20 points issue is noted :-)

2022-11-23 20:46 UTC, pconrad requested changes
Please add a story file for this; when adding new components that aren't part of the app yet, that's the only way to really visualize them.

You can look the other files under stories for examples.  There are two styles: .mdx and .js each with pros/cons.  The .mdx format is more expressive, but can be tougher to debug.  The .js format is a bit more constrained but easier to debug.  Either is fine.

2022-11-24 23:08 UTC, HansonYu23 commented
Added story file

2022-11-26 00:18 UTC, pconrad commented
> Added story file

You've added a story file, it's true.  But you didn't link to the deployed storybook entry.

And, the deployed storybook entry doesn't work:

https://ucsb-cs156-f22.github.io/f22-7pm-courses-docs-qa/storybook-qa/PersonalScheduleDropdown/?path=/docs/components-personalschedules-singlepersonalscheduledropdown--one-personal-schedule

At least all I saw was a blank screen. What I'm supposed to be able to see there is a demonstration of how the feature works.

2022-11-26 02:03 UTC, pconrad commented
Here's the correct storybook entry:

https://ucsb-cs156-f22.github.io/f22-7pm-courses-docs-qa/storybook-qa/PersonalScheduleDropdown/?path=/docs/components-personalschedules-singlepersonalscheduledropdown--one-personal-schedule

2022-11-26 02:09 UTC, pconrad requested changes
One small thing... ssd1 is for "Single Schedule Dropdown 1".

It doesn't make a different if it's just in a test, but if someone uses that code in the test as an example when they go to implement this on a page, it would interfere with the Local Storage Key for the single schedule dropdown.

So it would be good to search/replace ssd1 with something like psd1

2022-11-26 02:09 UTC, pconrad commented on frontend/src/tests/components/PersonalSchedules/SinglePersonalScheduleDropdown.test.js
> +        controlId="ssd1"
psd1 ?

2022-11-26 02:09 UTC, pconrad commented on frontend/src/tests/components/PersonalSchedules/SinglePersonalScheduleDropdown.test.js
> +        controlId="ssd1"
psd1 ?

2022-11-26 02:09 UTC, pconrad commented on frontend/src/tests/components/PersonalSchedules/SinglePersonalScheduleDropdown.test.js
> +        controlId="ssd1"
psd1?

2022-11-26 02:09 UTC, pconrad commented on frontend/src/tests/components/PersonalSchedules/SinglePersonalScheduleDropdown.test.js
> +        controlId="ssd1"
psd1 ?

2022-11-26 02:09 UTC, pconrad commented on frontend/src/tests/components/PersonalSchedules/SinglePersonalScheduleDropdown.test.js
> +        controlId="ssd1"
psd1 ?

2022-11-26 02:09 UTC, pconrad commented on frontend/src/tests/components/PersonalSchedules/SinglePersonalScheduleDropdown.test.js
> +        controlId="ssd1"
psd1 ?

2022-11-26 02:09 UTC, pconrad commented on frontend/src/tests/components/PersonalSchedules/SinglePersonalScheduleDropdown.test.js
> +        controlId="ssd1"
psd1 ?

2022-11-26 02:09 UTC, pconrad commented on frontend/src/tests/components/PersonalSchedules/SinglePersonalScheduleDropdown.test.js
> +        controlId="ssd1"
etc...

2022-11-26 02:35 UTC, HansonYu23 commented
Resolved all requested changes, storybook entry should now work as intended.

2022-11-27 02:17 UTC, pconrad approved these changes
LGTM

2022-11-27 02:18 UTC, merged