DC - FRONTEND: Personal Schedule names should be unique when taken together with the quarter
ucsb-cs156-f22/f22-7pm-courses pull request #53
Opened 2022-11-30 20:22 UTC by DylanC1222

<h1>Overview</h1>
In this PR, the changes made make it so that when a duplicate name and quarter personal schedule is attempted to be created, the frontend will now respond and tell the user that this is not allowed. This issue goes hand in hand with the backend issue of the same topic.

<h1>Details</h1>

If a duplicate name and quarter personal schedule is attempted to be created, a pop up shows up saying that the quarter and name are invalid. This can be tested using the unit tests and by going onto Heroku and attempting to create a personal schedule with the same name and quarter as another schedule. An example of this can be seen down below:

![Screen Shot 2022-11-30 at 12 18 12 PM](https://user-images.githubusercontent.com/77405374/204899746-fc360e91-4237-4e5f-ac3c-96e165fee2dc.png)

![Screen Shot 2022-11-30 at 12 18 25 PM](https://user-images.githubusercontent.com/77405374/204899737-796d4d58-e142-40af-88fe-49e75ed0aae7.png)

Closes #5

2022-11-30 20:39 UTC, HansonYu23 approved these changes, later dismissed
LGTM!

2022-12-01 01:37 UTC, mattn02 requested changes
Heroku functionality seems good, but you should remove the commented out code in your tests.

2022-12-01 01:37 UTC, mattn02 commented on frontend/src/tests/pages/PersonalSchedules/PersonalSchedulesCreatePage.test.js
> +        //const quarterField = document.querySelector("#PersonalScheduleForm-quarter");
You should remove the commented out code in your tests for clarity.

2022-12-01 01:43 UTC, mattn02 approved these changes
LGTM

2022-12-01 03:24 UTC, andrewpengucsb approved these changes
LGTM

2022-12-01 03:25 UTC, merged